config/routes.rb
Rails.application.routes.draw do

  resources :characters do
    collection do
      get :results
    end
  end

  devise_for :users
  scope module: 'static' do
    get :home
    get :dashboard
  end

  match 'positive_vote', to: 'vote#create_positive', via: :post
  match 'negative_vote', to: 'vote#create_negative', via: :post

  root 'static#home'

end

app/models/character.rb
class Character < ActiveRecord::Base
  # mount_uploader :photo, PhotoUploader

  # Concerns
  include Deletable

  # Model Validation
  validates_presence_of :slug

  # Model Relationships
  belongs_to :user
  has_many :votes

  # Class methods
  def self.load_characters

    loaded_successfully = []

    data_file = YAML.load_file(Rails.root.join(*(['lib', 'characters', 'characters.yml'])))
    data_file['characters'].each do |character_attributes|
      char = Character.where(slug: character_attributes["slug"]).first_or_create
      if char.update(character_attributes)
        loaded_successfully << character_attributes
      else
        puts "Error creating or updating: #{character_attributes}"
      end
    end

    {successful: loaded_successfully}

  end

  # Getters

  def positive_rating
    (self.votes.where(rating: 1).count.to_f / self.votes.count.to_f)*100 rescue 0
  end

end

app/models/concerns/deletable.rb
module Deletable
  extend ActiveSupport::Concern

  included do
    scope :current, -> { where deleted: false }
  end

  def destroy
    update_column :deleted, true
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :characters
  has_many :votes

  # Class Methods

  def voted_on_all?
    (self.votes.count == Character.current.count)
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base

  # Concerns
  include Deletable

  # Model Validation
  validates_presence_of :user_id, :character_id

  # Model Relationships
  belongs_to :user
  belongs_to :character

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :authenticate_user!
  before_action :verify_is_admin
  before_action :set_character, only: [:show, :edit, :update, :destroy]

  # Results
  def results
  end

  # GET /characters
  # GET /characters.json
  def index
    @characters = Character.current
  end

  # GET /characters/1
  # GET /characters/1.json
  def show
  end

  # GET /characters/new
  def new
    @character = Character.where(user_id: current_user.id).new
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters
  # POST /characters.json
  def create
    @character = Character.where(user_id: current_user.id).new(character_params)

    respond_to do |format|
      if @character.save
        format.html { redirect_to dashboard_path, notice: 'Character was successfully created.' }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1
  # PATCH/PUT /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character.destroy
    respond_to do |format|
      format.html { redirect_to characters_path, notice: 'Character was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def character_params
      params.require(:character).permit(:name, :slug, :fact1, :fact1_description, :fact2, :fact2_description, :fact3, :fact3_description, :photo)
    end

    def verify_is_admin
      (current_user.nil?) ? redirect_to(root_path) : (redirect_to(root_path) unless current_user.admin?)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def home
    redirect_to :dashboard if current_user
  end

  def dashboard
    redirect_to :home if !current_user
  end

end

app/controllers/vote_controller.rb
class VoteController < ApplicationController

  def create_positive
    Vote.find_or_initialize_by(user_id: current_user.id, character_id: params[:character]).update(rating: 1)
    redirect_to dashboard_path
  end

  def create_negative
    Vote.find_or_initialize_by(user_id: current_user.id, character_id: params[:character]).update(rating: 0)
    redirect_to dashboard_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

   def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/characters/_display.html.haml
= image_tag img, class: 'img-responsive centered', style: 'max-height: 300px; margin: auto'

app/views/characters/_form.html.haml
.well{ style: 'text-align: left; ' }
  = form_for(@character) do |f|
    - if @character.errors.any?
      #error_explanation
        %h2
          = pluralize(@character.errors.count, "error")
          prohibited this character from being saved:
        %ul
          - @character.errors.full_messages.each do |message|
            %li= message
    .form-group
      = f.label :name, class: 'control-label'
      = f.text_field :name, autofocus: true, class: 'form-control'
    .form-group
      = f.label :fact1, class: 'control-label'
      = f.text_area :fact1, class: 'form-control'
    .form-group
      = f.label :fact1_description, class: 'control-label'
      = f.text_area :fact1_description, class: 'form-control'
    .form-group
      = f.label :fact2, class: 'control-label'
      = f.text_area :fact2, class: 'form-control'
    .form-group
      = f.label :fact2_description, class: 'control-label'
      = f.text_area :fact2_description, class: 'form-control'
    .form-group
      = f.label :fact3, class: 'control-label'
      = f.text_area :fact3, class: 'form-control'
    .form-group
      = f.label :fact3_description, class: 'control-label'
      = f.text_area :fact3_description, class: 'form-control'
    .form-group
      = f.submit

app/views/characters/edit.html.haml
.well.well-sm.toonder-red-bcg.white
  %h1 Editing Character

= render 'form'

.well.well-sm
  = link_to 'Show', @character
  |
  = link_to 'Back', characters_path

app/views/characters/index.html.haml
.well
  %p#notice= notice
  %h1.dinosaur.toonder-red Listing Characters
  = link_to 'New Character', new_character_path, class: 'btn btn-primary btn-sm'

%div{style: 'background-color: white; margin: 40px;'}
  %table.table.table-striped
    %thead.toonder-red-bcg.white
      %tr
        %th
        %th.centered Name
        %th.centered Number of Votes
        %th.centered Positive Rating
        %th
    %tbody
      - @characters.each do |character|
        %tr
          %td= image_tag character.photo, class: 'img-responsive', style: 'max-width: 50px; margin: auto'
          %td= character.name
          %td= character.votes.count
          %td= character.positive_rating.nan? ? "--" : "#{character.positive_rating}%"
          %td
            = link_to 'Show', character, class: 'btn btn-primary btn-sm'
            = link_to 'Edit', edit_character_path(character), class: 'btn btn-warning btn-sm'

app/views/characters/new.html.haml
%h1 New Character

= render 'form'

= link_to 'Back', characters_path

app/views/characters/results.html.haml
.well
  %h1.toonder-red
    Looney Tunes vs. Scooby Doo
  .row
    .col-sm-3
      .retro1= render 'display', img: 'bugs-bunny1.png'
    .col-sm-6
      %p#show.btn.btn-primary{ 'data-target' => 'retro1' } Who's hotter?
      #retro1.hidden
        = render 'display', img: 'bugs-bunny1.png'
    .col-sm-3
      .retro1= render 'display', img: 'scooby-doo1.png'
  .row
    .col-sm-3
      .retro2= render 'display', img:  'Daffy_duck.png'
    .col-sm-6
      %p#show.btn.btn-primary{ 'data-target' => 'retro2' } Who's hotter?
      #retro2.hidden
        = render 'display', img:  'Daffy_duck.png'
    .col-sm-3
      .retro2= render 'display', img: 'Shaggy.png'
  .row
    .col-sm-3
      .retro3= render 'display', img: 'PepeLePew.png'
    .col-sm-6
      %p#show.btn.btn-primary{ 'data-target' => 'retro3' } Who's hotter?
      #retro3.hidden
        = render 'display', img: 'PepeLePew.png'
    .col-sm-3
      .retro3= render 'display', img: 'velma1.png'

- 5.times do
  %br

.well
  %h1.toonder-red
    Transformers vs TMNT
  .row
    .col-sm-3
      .super1= render 'display', img: 'optimus-prime1.png'
    .col-sm-6
      %p#show.btn.btn-primary{ 'data-target' => 'super1' } Who's hotter?
      #super1.hidden
        = render 'display', img: 'Michelangelo1.png'
    .col-sm-3
      .super1= render 'display', img: 'Michelangelo1.png'
  .row
    .col-sm-3
      .super2= render 'display', img: 'Megatron1.png'
    .col-sm-6
      %p#show.btn.btn-primary{ 'data-target' => 'super2' } Who's hotter?
      #super2.hidden= render 'display', img: 'Shredder1.png'
    .col-sm-3
      .super2= render 'display', img: 'Shredder1.png'
  .row
    .col-sm-3
      .super3= render 'display', img: 'BumbleBee1.png'
    .col-sm-6
      %p#show.btn.btn-primary{ 'data-target' => 'super3' } Who's hotter?
      #super3.hidden= render 'display', img: 'Splinter1.png'
    .col-sm-3
      .super3= render 'display', img: 'Splinter1.png'

- 5.times do
  %br

.well
  %h1.toonder-red
    Archer vs South Park
  .row
    .col-sm-3
      .mature1= render 'display', img: 'Pam1.png'
    .col-sm-6
      %p#show.btn.btn-primary{ 'data-target' => 'mature1' } Who's hotter?
      #mature1.hidden= render 'display', img: 'Pam1.png'
    .col-sm-3
      .mature1= render 'display', img: 'cartman2.png'
  .row
    .col-sm-3
      .mature2= render 'display', img: 'Malory2.png'
    .col-sm-6
      %p#show.btn.btn-primary{ 'data-target' => 'mature2' } Who's hotter?
      #mature2.hidden= render 'display', img: 'Malory2.png'
    .col-sm-3
      .mature2= render 'display', img: 'ButtersStotch1.png'
  .row
    .col-sm-3
      .mature3= render 'display', img: 'archer1.png'
    .col-sm-6
      %p#show.btn.btn-primary{ 'data-target' => 'mature3' } Who's hotter?
      #mature3.hidden= render 'display', img: 'archer1.png'
    .col-sm-3
      .mature3= render 'display', img: 'ChefSouthPark1.png'


- 5.times do
  %br

.well
  %h1.toonder-red
    Rugrats vs Spongbob Squarepants
  .row
    .col-sm-3
      .little1= render 'display', img: 'tommypickles1.png'
    .col-sm-6
      %p#show.btn.btn-primary{ 'data-target' => 'little1' } Who's hotter?
      #little1.hidden= render 'display', img: 'tommypickles1.png'
    .col-sm-3
      .little1= render 'display', img: 'SPONGEBOB1.png'
  .row
    .col-sm-3
      .little2= render 'display', img: 'Chuckie1.png'
    .col-sm-6
      %p#show.btn.btn-primary{ 'data-target' => 'little2' } Who's hotter?
      #little2.hidden= render 'display', img: 'Chuckie1.png'
    .col-sm-3
      .little2= render 'display', img: 'Patrick_Star1.png'
  .row
    .col-sm-3
      .little3= render 'display', img: 'Angelica1.png'
    .col-sm-6
      %p#show.btn.btn-primary{ 'data-target' => 'little3' } Who's hotter?
      #little3.hidden= render 'display', img: 'Angelica1.png'
    .col-sm-3
      .little3= render 'display', img: 'Squidward1.png'

%p#show-hottest.btn.btn-success Meet TV's HOTTEST cartoons
#hottest.hidden
  .well
    .row
      .col-sm-4.centered
        = render 'display', img: 'archer1.png'
      .col-sm-4.centered
        = render 'display', img: 'bugs-bunny1.png'
      .col-sm-4.centered
        = render 'display', img: 'Pam1.png'

%p#show-nottest.btn.btn-danger Meet TV's NOTtest cartoons
#nottest.hidden
  .well
    .row
      .col-sm-4.col-sm-offset-4
        = image_tag 'SPONGEBOB1.png', class: 'img-responsive'

- 5.times do
  %br

app/views/characters/show.html.haml
%p#notice
  = notice

.row
  .col-md-4.col-md-offset-4.col-sm-6.col-sm-offset-3.well
    = image_tag @character.photo, class: 'img-responsive', style: 'max-width: 150px; margin: auto;'
    %h3= @character.name
    %p.f300
      %span.f500= "#{@character.fact1.titlecase}: "
      %br
      = @character.fact1_description
    %p.f300
      %span.f500= "#{@character.fact2.titlecase}: "
      %br
      = @character.fact2_description
    %p.f300
      %span.f500= "#{@character.fact3.titlecase}: "
      %br
      = @character.fact3_description
    %br

.well.well-sm
  = link_to 'Edit', edit_character_path(@character)
  |
  = link_to 'Back', characters_path

app/views/layouts/_top_navigation.html.haml
/ Static navbar
%nav.navbar.navbar-default.navbar-static-top{ class: "#{(current_user and current_user.rueschman?) ? 'rueschman' : 'gray' }" }
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'TOONder', root_path, class: 'navbar-brand dinosaur toonder-red'
    #navbar.navbar-collapse.collapse
      %ul.nav.navbar-nav
      %ul.nav.navbar-nav.navbar-right
        - if current_user
          %li= link_to 'Logout', destroy_user_session_path, :method => :delete
        - else
          %li= link_to 'Login', new_user_session_path
          %li= link_to 'Signup', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
%head
  %title Toonder
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

%body{ class: "#{(current_user and current_user.rueschman?) ? 'rueschman' : 'hearts' }"}

= render partial: 'layouts/top_navigation'

.container-fluid.centered
  = yield